FROM sonatype/nexus3

ADD nexus-repository-apt-1.0.10.jar $NEXUS_HOME/system/net/staticsnow/nexus-repository-apt/1.0.10/nexus-repository-apt-1.0.10.jar
ADD nexus-repository-helm-0.0.7.jar $NEXUS_HOME/system/org/sonatype/nexus/plugins/nexus-repository-helm/0.0.7/nexus-repository-helm-0.0.7.jar
ADD nexus-core-feature-3.15.2-01-features.xml $NEXUS_HOME/system/org/sonatype/nexus/assemblies/nexus-core-feature/3.15.2-01/nexus-core-feature-3.15.2-01-features.xml