apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: nexus
  name: nexus
  namespace: default
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      qcloud-app: nexus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        qcloud-app: nexus
    spec:
      containers:
      - image: sonatype/nexus3:latest
        imagePullPolicy: IfNotPresent
        name: nexus
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /nexus-data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: ""
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        nfs:
          path: /data/nfs/nexus3
          server: ip

---
apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: nexus
  name: nexus
  namespace: default
spec:
  ports:
  - name: tcp-8081-8081
    nodePort: 19284
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    qcloud-app: nexus
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  namespace: default
spec:
  rules:
  - host: nexus.XXXX.com
    http:
      paths:
      - backend:
          serviceName: nexus
          servicePort: 8081
        path: /
      - backend:
          serviceName: nexus
          servicePort: 8081
        path: /*